# Default values for helm-charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  namespace: zk-client

redis:
  enabled: true
  architecture: standalone
  nameOverride: redis
  fullnameOverride: redis
  auth:
    enabled: true
  metrics:
    enabled: false
    serviceMonitor:
      enabled: false
  image:
    tag: "6.2.12-debian-11-r23"
  master:
    persistence:
      enabled: true
  replica:
    persistence:
      enabled: true
    resources:
      limits:
        cpu: 1
        memory: 1Gi
  sentinel:
    enabled: false
  commonConfiguration: |-
    # Enable AOF https://redis.io/topics/persistence#append-only-file
    appendonly yes
    maxmemory-policy volatile-ttl
    maxmemory  800M
    # Disable RDB persistence, AOF persistence already enabled.
    save ""
  

zk-scenario-manager:
  serviceConfigs:
    logs:
      color: true
      level: ERROR

zk-operator:
  serviceConfigs:
    logs:
      color: true
      level: ERROR

zk-otlp-receiver:
  serviceConfigs:
    logs:
      color: true
      level: ERROR
