{
 "title": "Load-test Data",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "API level latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(rate(loadtest__http_request_duration_seconds_count{route=\"/highload\"}[$__rate_interval]))",
     "legendFormat": "highload"
    },
    {
     "expr": "avg(rate(loadtest__http_request_duration_seconds_count{route=\"/lowload\"}[$__rate_interval]))",
     "legendFormat": "lowload"
    },
    {
     "expr": "avg(rate(loadtest__http_request_duration_seconds_count{route=\"/highcpu\"}[$__rate_interval]))",
     "legendFormat": "highcpu"
    },
    {
     "expr": "avg(rate(loadtest__http_request_duration_seconds_count{route=\"/highmem\"}[$__rate_interval]))",
     "legendFormat": "highmem"
    }
   ]
  },
  {
   "title": "Autoscaler",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_current_replicas{}",
     "legendFormat": "Current Replicas {{horizontalpodautoscaler}}"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_max_replicas{}",
     "legendFormat": "Max replicas"
    }
   ]
  },
  {
   "title": "Data Inflow",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    { "expr": "sum(lowload_counter)", "legendFormat": "lowload Counter" },
    { "expr": "sum(highload_counter)", "legendFormat": "highload Counter" },
    { "expr": "sum(highcpu_counter)", "legendFormat": "highcpu Counter" },
    { "expr": "sum(highmem_counter)", "legendFormat": "highmem Counter" }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "cluster:node_cpu:ratio{} * 1000",
     "legendFormat": "Node CPU utilization"
    },
    {
     "expr": "avg(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"app\"}) * 1000",
     "legendFormat": "Avg CPU Usage - Container"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_target_metric{}",
     "legendFormat": "container Scaling Target%"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "k6_http_req_duration_avg{status=\"200\"}",
     "legendFormat": "Avg {{url}}"
    },
    {
     "expr": "k6_http_req_duration_p95{status=\"200\"}",
     "legendFormat": "P95  {{url}}"
    }
   ]
  },
  {
   "title": "K6 Fire rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum by(expected_response) (changes(k6_http_reqs{url=~\".*highload\"}[$__interval]))",
     "legendFormat": "highload {{expected_response}}"
    },
    {
     "expr": "sum by(expected_response) (changes(k6_http_reqs{url=~\".*lowload\"}[$__interval]))",
     "legendFormat": "lowload {{expected_response}}"
    }
   ]
  }
 ]
}