apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pl-vizier-metadata-cluster-binding
  labels:
    app: pl-monitoring
    component: vizier
  {{- include "zk-ebpf.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'pl-vizier-metadata'
subjects:
- kind: ServiceAccount
  name: 'vizier-metadata-service-account'
  namespace: '{{ .Release.Namespace }}'