apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zk-ebpf.fullname" . }}-zpixie-configmap
  labels:
    app: pl-monitoring
    component: vizier
  {{- include "zk-ebpf.labels" . | nindent 4 }}
data:
  zpixie-configmap.yaml: {{ .Values.zpixieConfigmap.zpixieConfigmapYaml | toYaml
    | indent 1 }}