apiVersion: v1
data:
  zk-client-db-configmap.yaml: |-
    redis:
      port: 6379
      readTimeout: 20

    postgres:
      host: postgreshost
      port: 1234
      user: postgres
      password: abc
      dbname: 1
kind: ConfigMap
metadata:
  labels:
    app: pl-monitoring
    component: vizier
  name: zk-client-db-configmap
  namespace: pl
---
apiVersion: v1
data:
  zpixie-configmap.yaml: "allowNonTraced: false\nhttp: \n  enabled: true\n  traceEnabled: true\n  allowNonTraced: false\nmysql: \n  enabled: true\n  traceEnabled: true\n  allowNonTraced: false\npgsql: \n  enabled: true\n  traceEnabled: true\n  allowNonTraced: false"
kind: ConfigMap
metadata:
  labels:
    app: pl-monitoring
    component: vizier
  name: zpixie-configmap
  namespace: pl
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: pl-monitoring
    component: vizier
  name: vizier-pem
  namespace: pl
spec:
  selector:
    matchLabels:
      app: pl-monitoring
      component: vizier
      name: vizier-pem
  template:
    metadata:
      labels:
        app: pl-monitoring
        component: vizier
        name: vizier-pem
        plane: data
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: Exists
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
              - matchExpressions:
                  - key: beta.kubernetes.io/os
                    operator: Exists
                  - key: beta.kubernetes.io/os
                    operator: In
                    values:
                      - linux
#      nodeSelector:
#        beta.kubernetes.io/instance-type: e2-standard-16
      containers:
        - args: []
          env:
            - name: TCMALLOC_SAMPLE_PARAMETER
              value: "1048576"
            - name: PL_CLIENT_TLS_CERT
              value: /certs/client.crt
            - name: PL_CLIENT_TLS_KEY
              value: /certs/client.key
            - name: PL_TLS_CA_CERT
              value: /certs/ca.crt
            - name: PL_DISABLE_SSL
              value: "false"
            - name: PL_HOST_PATH
              value: /host
            - name: PL_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: PL_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: PL_HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: PL_JWT_SIGNING_KEY
              valueFrom:
                secretKeyRef:
                  key: jwt-signing-key
                  name: pl-cluster-secrets
            - name: PL_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redis-password
                  name: redis
            - name: PL_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  key: redisHost
                  name: zk-redis-config
            - name: PL_VIZIER_ID
              valueFrom:
                secretKeyRef:
                  key: cluster-id
                  name: pl-cluster-secrets
                  optional: true
            - name: PL_VIZIER_NAME
              valueFrom:
                secretKeyRef:
                  key: cluster-name
                  name: pl-cluster-secrets
                  optional: true
            - name: PL_CLOCK_CONVERTER
              value: default
          image: gcr.io/pixie-oss/pixie-prod/vizier/pem_image:0.14.5
          imagePullPolicy: Always
          name: pem
          resources: {}
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
                - SYS_ADMIN
            privileged: true
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - mountPath: /host
              name: host-root
              readOnly: true
            - mountPath: /sys
              name: sys
              readOnly: true
            - mountPath: /certs
              name: certs
            - mountPath: /opt/zk-client-db-configmap.yaml
              name: zk-client-db-configmap
              subPath: zk-client-db-configmap.yaml
            - mountPath: /opt/zpixie-configmap.yaml
              name: zpixie-configmap
              subPath: zpixie-configmap.yaml
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      hostPID: true
      initContainers:
        - command:
            - sh
            - -c
            - 'set -x; URL="https://${SERVICE_NAME}:${SERVICE_PORT}/healthz"; until [ $(curl -m 0.5 -s -o /dev/null -w "%{http_code}" -k ${URL}) -eq 200 ]; do echo "waiting for ${URL}"; sleep 2; done; '
          env:
            - name: SERVICE_NAME
              value: vizier-query-broker-svc
            - name: SERVICE_PORT
              value: "50300"
          image: gcr.io/pixie-oss/pixie-dev-public/curl:multiarch-7.87.0@sha256:f7f265d5c64eb4463a43a99b6bf773f9e61a50aaa7cefaf564f43e42549a01dd
          name: qb-wait
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 10
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
        - effect: NoExecute
          operator: Exists
        - effect: NoSchedule
          operator: Exists
      volumes:
        - hostPath:
            path: /
            type: Directory
          name: host-root
        - hostPath:
            path: /sys
            type: Directory
          name: sys
        - name: certs
          secret:
            secretName: service-tls-certs
        - configMap:
            name: zk-client-db-configmap
          name: zk-client-db-configmap
        - configMap:
            name: zpixie-configmap
          name: zpixie-configmap
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 20
    type: RollingUpdate
#---
#apiVersion: apps/v1
#kind: DaemonSet
#metadata:
#  labels:
#    app: pl-monitoring
#    component: vizier
#  name: vizier-pem
#  namespace: pl
#spec:
#  selector:
#    matchLabels:
#      app: pl-monitoring
#      component: vizier
#      name: vizier-pem
#  template:
#    metadata:
#      labels:
#        app: pl-monitoring
#        component: vizier
#        name: vizier-pem
#        plane: data
#    spec:
#      affinity:
#        nodeAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            nodeSelectorTerms:
#              - matchExpressions:
#                  - key: kubernetes.io/os
#                    operator: Exists
#                  - key: kubernetes.io/os
#                    operator: In
#                    values:
#                      - linux
#              - matchExpressions:
#                  - key: beta.kubernetes.io/os
#                    operator: Exists
#                  - key: beta.kubernetes.io/os
#                    operator: In
#                    values:
#                      - linux
#              - matchExpressions:
#                  - key: beta.kubernetes.io/arch
#                    operator: In
#                    values:
#                      - arm64
#      nodeSelector:
#        beta.kubernetes.io/arch: arm64
#        beta.kubernetes.io/instance-type: e2-standard-16
#      containers:
#        - args: []
#          env:
#            - name: TCMALLOC_SAMPLE_PARAMETER
#              value: "1048576"
#            - name: PL_CLIENT_TLS_CERT
#              value: /certs/client.crt
#            - name: PL_CLIENT_TLS_KEY
#              value: /certs/client.key
#            - name: PL_TLS_CA_CERT
#              value: /certs/ca.crt
#            - name: PL_DISABLE_SSL
#              value: "false"
#            - name: PL_HOST_PATH
#              value: /host
#            - name: PL_POD_NAME
#              valueFrom:
#                fieldRef:
#                  fieldPath: metadata.name
#            - name: PL_POD_NAMESPACE
#              valueFrom:
#                fieldRef:
#                  fieldPath: metadata.namespace
#            - name: PL_HOST_IP
#              valueFrom:
#                fieldRef:
#                  fieldPath: status.hostIP
#            - name: PL_JWT_SIGNING_KEY
#              valueFrom:
#                secretKeyRef:
#                  key: jwt-signing-key
#                  name: pl-cluster-secrets
#            - name: PL_REDIS_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  key: redis-password
#                  name: redis
#            - name: PL_REDIS_HOST
#              valueFrom:
#                configMapKeyRef:
#                  key: redisHost
#                  name: zk-redis-config
#            - name: PL_VIZIER_ID
#              valueFrom:
#                secretKeyRef:
#                  key: cluster-id
#                  name: pl-cluster-secrets
#                  optional: true
#            - name: PL_VIZIER_NAME
#              valueFrom:
#                secretKeyRef:
#                  key: cluster-name
#                  name: pl-cluster-secrets
#                  optional: true
#            - name: PL_CLOCK_CONVERTER
#              value: default
#          image: us-west1-docker.pkg.dev/black-scope-358204/zk-client/gcr.io/pixie-oss/pixie-dev/vizier/pem_image:0.1.0-ebpf
#          imagePullPolicy: Always
#          name: pem
#          resources: {}
#          securityContext:
#            capabilities:
#              add:
#                - SYS_PTRACE
#                - SYS_ADMIN
#            privileged: true
#            seccompProfile:
#              type: RuntimeDefault
#          volumeMounts:
#            - mountPath: /host
#              name: host-root
#              readOnly: true
#            - mountPath: /sys
#              name: sys
#              readOnly: true
#            - mountPath: /certs
#              name: certs
#            - mountPath: /opt/zk-client-db-configmap.yaml
#              name: zk-client-db-configmap
#              subPath: zk-client-db-configmap.yaml
#            - mountPath: /opt/zpixie-configmap.yaml
#              name: zpixie-configmap
#              subPath: zpixie-configmap.yaml
#      dnsPolicy: ClusterFirstWithHostNet
#      hostNetwork: true
#      hostPID: true
#      initContainers:
#        - command:
#            - sh
#            - -c
#            - 'set -x; URL="https://${SERVICE_NAME}:${SERVICE_PORT}/healthz"; until [ $(curl -m 0.5 -s -o /dev/null -w "%{http_code}" -k ${URL}) -eq 200 ]; do echo "waiting for ${URL}"; sleep 2; done; '
#          env:
#            - name: SERVICE_NAME
#              value: vizier-query-broker-svc
#            - name: SERVICE_PORT
#              value: "50300"
#          image: gcr.io/pixie-oss/pixie-dev-public/curl:multiarch-7.87.0@sha256:f7f265d5c64eb4463a43a99b6bf773f9e61a50aaa7cefaf564f43e42549a01dd
#          name: qb-wait
#          securityContext:
#            allowPrivilegeEscalation: false
#            capabilities:
#              drop:
#                - ALL
#            seccompProfile:
#              type: RuntimeDefault
#      securityContext:
#        seccompProfile:
#          type: RuntimeDefault
#      terminationGracePeriodSeconds: 10
#      tolerations:
#        - effect: NoSchedule
#          key: node-role.kubernetes.io/master
#        - effect: NoExecute
#          operator: Exists
#        - effect: NoSchedule
#          operator: Exists
#      volumes:
#        - hostPath:
#            path: /
#            type: Directory
#          name: host-root
#        - hostPath:
#            path: /sys
#            type: Directory
#          name: sys
#        - name: certs
#          secret:
#            secretName: service-tls-certs
#        - configMap:
#            name: zk-client-db-configmap
#          name: zk-client-db-configmap
#        - configMap:
#            name: zpixie-configmap
#          name: zpixie-configmap
#  updateStrategy:
#    rollingUpdate:
#      maxUnavailable: 20
#    type: RollingUpdate
