name: prod-build-push
on:
  push:
    tags: #r/<ENVIRONMENT>/<DOCKER-TAG-OR-VERSION>
      - 'prod/**'
  workflow_call:
    inputs:
      TAG:
        type: string
        required: true
env:
  APP_NAME: ${{ vars.APP_NAME }}
  GIT_TAG: ${{ inputs.TAG || github.ref }}

jobs:
  init:
    uses: zerok-ai/zk-git-actions/.github/workflows/zk-prod-init.yml@main
    with:
      ENVIRONMENT: ${{ github.event.inputs.ENV }}
      GIT_TAG: ${{ GIT_TAG }}
      DOCKER_TAG: ${{ github.event.inputs.DOCKER_TAG }}

  # build helm charts and publish to helm repository
  helm-push:
    uses: zerok-ai/zk-git-actions/.github/workflows/zk-helm-publish.yml@main
    with:
      HELM_VERSION: ${{ needs.init.outputs.VERSION }}
      ENVIRONMENT: ${{ needs.init.outputs.ENVIRONMENT }}
      DOCKER_IDENTIFIER: ${{ needs.init.outputs.ENVIRONMENT }}
      HELM_BUCKET_NAME: ${{ needs.init.outputs.HELM_BUCKET_NAME }}
      HELM_BUCKET_URL: ${{ needs.init.outputs.HELM_BUCKET_URL }}
      PROJECT_ID: ${{ needs.init.outputs.PROJECT_ID }}
    secrets:
      AWS_ACCESS_ID: ${{ secrets.AWS_ACCESS_ID }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
    needs: init
