name: prod-build-push
on:
  push:
    tags: #r/<ENVIRONMENT>/<DOCKER-TAG-OR-VERSION>
      - 'prod/**'
env:
  APP_NAME: ${{ vars.APP_NAME }}
#  # Uncomment the following code for testing
#  workflow_dispatch:
#    inputs:
#      DOCKER_TAG:
#        description: 'Docker Image Tag'
#        required: true
#        default: '0.0.9-helmtest'
#      ENV:
#        description: 'ENV'
#        required: true
#        default: 'poc'
jobs:
  init:
    uses: zerok-ai/zk-git-actions/.github/workflows/zk-prod-init.yml@main
    with:
      ENVIRONMENT: ${{ github.event.inputs.ENV }}
      GIT_TAG: ${{ github.ref }}
      DOCKER_TAG: ${{ github.event.inputs.DOCKER_TAG }}

  # build helm charts and publish to helm repository
  helm-push:
    uses: zerok-ai/zk-git-actions/.github/workflows/zk-helm-publish.yml@main
    with:
      HELM_VERSION: ${{ needs.init.outputs.VERSION }}
      ENVIRONMENT: ${{ needs.init.outputs.ENVIRONMENT }}
      DOCKER_IDENTIFIER: ${{ needs.init.outputs.ENVIRONMENT }}
      HELM_BUCKET_NAME: ${{ needs.init.outputs.HELM_BUCKET_NAME }}
      HELM_BUCKET_URL: ${{ needs.init.outputs.HELM_BUCKET_URL }}
      PROJECT_ID: ${{ needs.init.outputs.PROJECT_ID }}
    secrets:
      AWS_ACCESS_ID: ${{ secrets.AWS_ACCESS_ID }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
    needs: init

#  helm-publish:
#    needs: init
#    runs-on: zk-self-hosted
#    environment:
#      name: ${{ needs.init.outputs.ENVIRONMENT }}
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
#          aws-region: ${{ vars.AWS_REGION }}
#
#      - name: s3 sync repo
#        run: |-
#          echo "APP_NAME=$APP_NAME"
#          aws s3 sync --debug ${{ needs.init.outputs.HELM_BUCKET_NAME }}/zk-client/$APP_NAME .
