name: cli-publish
on:
  push:
    tags: #r/<ENVIRONMENT>/<DOCKER-TAG-OR-VERSION>
      - 'cli/**'

#  # Uncomment the following code for testing
#  workflow_dispatch:
#    inputs:
#      DOCKER_TAG:
#        description: 'Docker Image Tag'
#        required: true
#        default: '0.0.9-helmtest'
#      ENV:
#        description: 'ENV'
#        required: true
#        default: 'poc'
jobs:
  init:
    uses: zerok-ai/zk-git-actions/.github/workflows/zk-prod-init.yml@main
    with:
      ENVIRONMENT: ${{ github.event.inputs.ENV }}
      GIT_TAG: ${{ github.ref }}
      DOCKER_TAG: ${{ github.event.inputs.DOCKER_TAG }}

  # publish executables to S3
  publish:
    uses: zerok-ai/zk-git-actions/.github/workflows/zk-file-build-publish.yml@main
    with:
      ENVIRONMENT: ${{ needs.init.outputs.ENVIRONMENT }}
      ARTIFACT_FOLDER_NAME: ${{ format('builds/{0}', needs.init.outputs.VERSION) }}
      VERSION: ${{ needs.init.outputs.VERSION }}
    secrets:
      AWS_ACCESS_ID: ${{ secrets.AWS_ACCESS_ID }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
    needs: init